name: CI Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      PYTHON_VERSION:
        required: false
        type: string
        default: "3.10"

      ENABLE_SONAR:
        required: false
        type: boolean
        default: false

      ENABLE_CODE_CLIMATE:
        required: false
        type: boolean
        default: false

      ENABLE_SLACK:
        required: false
        type: boolean
        default: false

      ENFORCE_PYLINT:
        required: false
        type: boolean
        default: true

      ENFORCE_BLACK:
        required: false
        type: boolean
        default: true

      ENFORCE_FLAKE8:
        required: false
        type: boolean
        default: true

      ENFORCE_DIVE:
        required: false
        type: boolean
        default: true

      ENFORCE_BANDIT:
        required: false
        type: boolean
        default: true

      DIVE_CONFIG:
        required: false
        type: string
        default: ""

      CONTAINER_REGISTRY:
        required: true
        type: string
        default: "docker.io"

      CONTAINER_REPOSITORY:
        required: true
        type: string
        default: "fakusima/user_service"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@
